# For development purposes only
name: cheapskate

services:

  database:
    image: postgres:18.3-alpine
    volumes:
      - database:/var/lib/postgresql/
    env_file:
      - src/.env
    environment:
      - TZ=Europe/Moscow
    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'


volumes:
  database:
