FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY src/backend ./backend
COPY src/utils ./utils
COPY pyproject.toml poetry.lock src/.env entrypoint.sh src/api.py ./

RUN pip3 install --upgrade pip
RUN pip3 install poetry --no-cache-dir
RUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi

RUN chmod +x entrypoint.sh

ENTRYPOINT [ "/app/entrypoint.sh" ]