# For development purposes only

version: '3.9'

services:

  cheapskate_db:
    image: postgres:15-alpine
    volumes:
      - cheapskate_database:/var/lib/postgresql/data/
    env_file:
      - src/.env
    environment:
      - TZ=Europe/Moscow
    ports:
      - '5432:5432'

  cheapskate_redis:
    image: redis
    ports:
      - '6379:6379'


volumes:
  cheapskate_database:
