[tool.poetry]
name = "cheapskate"
version = "0.1.0"
description = "Financial control telegram bot and API"
authors = ["Ilya Malashenko <melax08@yandex.ru>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "^20.4"
python-dotenv = "^1.0.0"
fastapi = "^0.101.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
pydantic-settings = "^2.0.3"
aiosqlite = "^0.19.0"
sqlalchemy = "^2.0.20"
alembic = "^1.11.3"
greenlet = "^2.0.2"
aiohttp = "^3.8.5"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
flake8 = "^6.1.0"
pre-commit = "^3.3.3"
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
