name: cheapskate

services:

  database:
    image: postgres:18.3-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/
    env_file:
      - ../src/.env
    environment:
      - TZ=Europe/Moscow

  redis:
    image: redis
    restart: always

  migrations:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    entrypoint: infra/entrypoint_api_migrations.sh
    depends_on:
      database:
          condition: service_started
    env_file:
      - ../src/.env
    environment:
      TZ: Europe/Moscow
      DB_HOST: database
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    entrypoint: infra/entrypoint_api.sh
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
      database:
        condition: service_started
    env_file:
      - ../src/.env
    environment:
      TZ: Europe/Moscow
      DB_HOST: database
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

  bot:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    entrypoint: infra/entrypoint_bot.sh
    restart: always
    volumes:
      - ./.data/:/.data/
    depends_on:
      - backend
      - redis
    env_file:
      - ../src/.env
    environment:
      TZ: Europe/Moscow
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

volumes:
  database:
