import os

from dotenv import load_dotenv

load_dotenv()

# API settings
API_VERSION = "v1"
API_PATH = f"/api/{API_VERSION}"
API_HOST = os.getenv("HOST_API", default="127.0.0.1")
API_URL = f"http://{API_HOST}:8000{API_PATH}/"

# Root paths
CATEGORIES_PATH = "category"
EXPENSE_PATH = "expense"
CURRENCY_PATH = "currency"
SETTINGS_PATH = "settings"
STATISTIC_ROOT_PATH = "statistic"
REPORT_ROOT_PATH = "report"
USER_PATH = "user"

# Relative paths
MONEY_LEFT_PATH = "/money_left"
TODAY_EXPENSE_PATH = "/today"
PERIOD_EXPENSE_PATH = "/period"
STATISTIC_PATH = "/statistic"
SET_DEFAULT_CURRENCY_PATH = "/set-default-currency"
SET_BUDGET_PATH = "/set-budget"
UPDATE_TABLE_PATH = "/update-report"
REGISTER_USER_FROM_TELEGRAM_PATH = "/telegram-register"


# Full paths
MONEY_LEFT_FULL_PATH = STATISTIC_ROOT_PATH + MONEY_LEFT_PATH
TODAY_EXPENSE_FULL_PATH = STATISTIC_ROOT_PATH + TODAY_EXPENSE_PATH
PERIOD_EXPENSE_FULL_PATH = STATISTIC_ROOT_PATH + PERIOD_EXPENSE_PATH
STATISTIC_FULL_PATH = STATISTIC_ROOT_PATH + STATISTIC_PATH
SET_DEFAULT_CURRENCY_FULL_PATH = SETTINGS_PATH + SET_DEFAULT_CURRENCY_PATH
SET_BUDGET_FULL_PATH = SETTINGS_PATH + SET_BUDGET_PATH
UPDATE_TABLE_FULL_PATH = REPORT_ROOT_PATH + UPDATE_TABLE_PATH
REGISTER_USER_FROM_TELEGRAM_FULL_PATH = USER_PATH + REGISTER_USER_FROM_TELEGRAM_PATH
