from decimal import Decimal

# Common constants for bot and API
MAX_CATEGORY_NAME_LENGTH: int = 100
MINIMUM_EXPENSE_AMOUNT: Decimal = Decimal("0.001")
MAX_CURRENCY_NAME_LENGTH: int = 50
MAX_EXPENSE_DESCRIPTION_LENGTH: int = 300
CURRENCY_LETTER_CODE_LENGTH: int = 3
COUNTRY_LENGTH: int = 50
MINIMUM_BUDGET_AMOUNT: int = 1
