"""Add is_visible to category

Revision ID: 1da02ff3a5a2
Revises: 62f0822c7ee0
Create Date: 2025-10-05 16:02:17.530769

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1da02ff3a5a2"
down_revision: str | None = "62f0822c7ee0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category", sa.Column("is_visible", sa.Boolean(), server_default="true", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "is_visible")
    # ### end Alembic commands ###
