"""Add restrict in expense category on delete

Revision ID: 22c1643b244b
Revises: 88ed4b8edf9f
Create Date: 2026-07-10 13:45:05.962649

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22c1643b244b"
down_revision: str | None = "88ed4b8edf9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("expense_category_id_fkey"), "expense", type_="foreignkey")
    op.create_foreign_key(None, "expense", "category", ["category_id"], ["id"], ondelete="RESTRICT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "expense", type_="foreignkey")
    op.create_foreign_key(
        op.f("expense_category_id_fkey"), "expense", "category", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###
