"""Add settings model

Revision ID: 23ad25779d83
Revises: 04937da8fd99
Create Date: 2024-04-25 19:57:21.410411

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23ad25779d83"
down_revision: str | None = "04937da8fd99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setting",
        sa.Column("budget", sa.Integer(), nullable=False),
        sa.Column("default_currency_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["default_currency_id"],
            ["currency.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("setting")
    # ### end Alembic commands ###
