"""Expense amount float to decimal

Revision ID: 929c00be12a7
Revises: 23ad25779d83
Create Date: 2024-10-23 15:14:46.481496

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "929c00be12a7"
down_revision: str | None = "23ad25779d83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expense",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=3),
        existing_nullable=False,
    )
    op.alter_column("setting", "default_currency_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("setting", "default_currency_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "expense",
        "amount",
        existing_type=sa.DECIMAL(precision=15, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
