"""Budget amount integer to decimal

Revision ID: 9a933b32243f
Revises: 929c00be12a7
Create Date: 2024-10-23 15:24:18.978988

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a933b32243f"
down_revision: str | None = "929c00be12a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "setting",
        "budget",
        existing_type=sa.INTEGER(),
        type_=sa.DECIMAL(precision=15, scale=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "setting",
        "budget",
        existing_type=sa.DECIMAL(precision=15, scale=3),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
