"""Add description field to the expense

Revision ID: b91e5fe245f7
Revises: 22c1643b244b
Create Date: 2026-07-17 16:03:18.661405

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b91e5fe245f7"
down_revision: Union[str, None] = "22c1643b244b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expense", sa.Column("description", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expense", "description")
    # ### end Alembic commands ###
