"""Add currency symbol

Revision ID: bdcac933687a
Revises: b91e5fe245f7
Create Date: 2026-08-05 00:20:46.209710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdcac933687a"
down_revision: str | None = "b91e5fe245f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("currency", sa.Column("symbol", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("currency", "symbol")
    # ### end Alembic commands ###
